services:
    App\Commands\Handlers\ReserveSingleFlatHandler:
        tags:
            - { name: tactician.handler, command: App\Commands\ReserveSingleFlatHandler }
    App\Commands\Handlers\ReserveMultipleFlatsHandler:
        tags:
            - { name: tactician.handler, command: App\Commands\ReserveMultipleFlatsCommand }
